#This is the lexicon for Bethany E. Toma's Geobong language
[metadata]
last_edited = 2019-06-09

[[lexicon]]
    word = "teuň"
    IPA = "t̻ɯn̺"
    english = ["it", "they", "them"]
    meta.date_added = 2019-06-09
    grammar.POS="pronoun"
    grammar.person = "3rd"
    grammar.noun_class="natural force"
    [grammar.reflexive]
        word = "teudteuň"
        IPA = "t̻ɯd̻t̻ɯn̺"
        english = ["itself", "they", "them"]
        notes = "used for the subject, not the object"

[[lexicon]]
    word = "ameu"
    IPA = "m̩ɯ"
    english = ["he","she","it","they","him","her","them"]
    meta.date_added = 2019-06-09
    grammar.POS = "pronoun"
    grammar.person = "3rd"
    grammar.noun_class = "non-goblin intelligence"
    [grammar.reflexive]
        word = "meum"
        IPA = "mɯm"
        english = ["himself","herself","itself","themselves"]
        notes = "used for the subject, not the object"

[[lexicon]]
    word = "eog"
    IPA = "ɤg"
    english = ["he","she","it","they","him","her","them"]
    meta.date_added = 2019-06-09
    grammar.POS = "pronoun"
    grammar.person = "3rd"
    grammar.noun_class = "goblin"
    [grammar.reflexive]
        word = "geog"
        IPA = "gɤg"
        english = ["himself","herself","itself","themselves"]
        notes = "used for the subject, not the object"

[[lexicon]]
    word = "šu"
    IPA = "s̺u"
    english = ["he","she","it","they","him","her","them"]
    meta.date_added = 2019-06-09
    grammar.POS = "pronoun"
    grammar.person = "3rd"
    grammar.noun_class = "animal"
    [grammar.reflexive]
        word = "šuš"
        IPA = "s̺us̺"
        english = ["himself","herself","itself","themselves"]
        notes = "used for the subject, not the object"

[[lexicon]]
    word = "him"
    IPA = "ʔim"
    english = ["it", "they", "them"]
    meta.date_added = 2019-06-09
    grammar.POS = "pronoun"
    grammar.person = "3rd"
    grammar.noun_class = "inanimate"
    [grammar.reflexive]
        word = "himim"
        IPA = "ʔimim"
        english = ["itself", "themselves"]
        notes = "used for the subject, not the object"

[[lexicon]]
    word = "es"
    IPA = "es̻"
    english = ["it", "they", "them"]
    meta.date_added = 2019-06-09
    grammar.POS = "pronoun"
    grammar.person = "3rd"
    grammar.noun_class = "abstract"
    [grammar.reflexive]
        word = "ses"
        IPA = "s̻es̻"
        english = ["itself", "themselves"]
        notes = "used for the subject, not the object"

[[lexicon]]
    word = "teď"
    IPA = "t̻ed̺"
    english = ["I","me"]
    meta.date_added = 2019-06-09
    grammar.POS = "pronoun"
    grammar.person = "1st"
    [grammar.reflexive]
        word = "teteď"
        IPA = "t̻et̻ed̺"
        english = ["myself"]
        notes = "used for the subject, not the object"

[[lexicon]]
    word = "kar"
    IPA = "kɹ̩"
    english = ["you"]
    meta.date_added = 2019-06-09
    grammar.POS = "pronoun"
    grammar.person = "2nd"
    [grammar.reflexive]
        word = "karkar"
        IPA = "kɹ̩kɹ̩"
        english = ["yourself", "yourselves"]
        notes = "used for the subject, not the object"

[[lexicon]]
    word = "łemp"
    IPA = "ɬ̻eb͡p"
    english = ["to trip", "to obstruct", "to impede", "to cause to stumble","stumbling","impeded","clumsy"]
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "łempstu"
        IPA = "ɬ̻eb͡ps̻t̻u"

[[lexicon]]
    word = "beu"
    IPA = "bɯ"
    english = ["berry", "cherry", "grape", "currant", "soft fruit"]
    notes = "describes any fruit small enough for a number that is difficult to easily count to be held in the palm, regardless of whether they are botanically berries or not"
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "inanimate"

[[lexicon]]
    word = "kał"
    IPA = "kɬ̻̩"
    english = ["red", "to redden", "to make red"]
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "kastu"
        IPA = "ks̻̩t̻u"
        english = ["red", "redness", "the color red"]

[[lexicon]]
    word = "ot"
    IPA = "ot̻"
    english = ["to sit", "to seat", "to make sit", "to cause to sit down", "sitting", "seated"]
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "octu"
        IPA = "ot͡s̻t̻u"
        english = ["sitting", "seat", "chair", "stump", "sitting-place"]

[[lexicon]]
    word = "řim"
    IPA = "ɹ̺im"
    english = ["to make run", "to cause to run"]
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "řibstu"
        IPA = "ɹ̺ib͡ps̻t̻u"
        english = ["running", "run", "exercise"]

[[lexicon]]
    word = "śe"
    IPA = "çe"
    english = ["to do", "to make", "to cause", "to bring about", "to make happen", "to cause to occur", "to create", "to build"]
    notes = "the latter meanings of \"to build, to create\" are only applicable when it comes to abstract concepts, not physical inanimate objects"
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "śestu"
        IPA = "çes̻t̻u"
        english = ["action", "behavior", "activity", "production", "happening", "happenstance", "occurance", "event", "eventuality"]

[[lexicon]]
    word = "řu"
    IPA = "ɹ̺u"
    english = ["to cook", "to prepare (food)"]
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "řustu"
        IPA = "ɹ̺us̻t̻u"
        english = ["cooking", "cooking supplies"]

[[lexicon]]
    word = "ŋuž"
    IPA = "ŋud͡z̺"
    english = ["fish", "swimming thing"]
    notes = "describes any vaguely fat-looking swimming water creature -- any swimming creature that isn't better described as a snake/eel, frog/toad, or waterbug"
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "animal"

[[lexicon]]
    word = "šřeoď"
    IPA = "s̺ɹ̺ɤd̺"
    english = ["snake", "eel", "worm", "serpent", "tadpole"]
    notes = "describes any long, slim, flexible animal -- anything snake-shaped, regardless of its home environment"
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "animal"

[[lexicon]]
    word = "geob" 
    IPA = "gɤb"
    english = ["goblin"]
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "goblin"

[[lexicon]]
    word = "geoboŋ"
    IPA = "gɤboŋ"
    english = ["Gebong", "the Goblin language", "goblin-speak"]
    notes = "Often has a somewhat pejorative connotation; most goblin communities exist in some degree of di- or tri-glossia, with Geobong serving as the basolect while the local non-goblin language serves as the acrolect (with varying degrees of mixture serving as mesolect)"
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "abstract"

[[lexicon]]
    word = "stu"
    IPA = "s̻t̻u"
    english = ["stuff", "things", "shit", "whatever"]
    notes = "contextually-variable, can refer to just about anything with the proper context"
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "any"

[[lexicon]]
    word = "že"
    IPA = "d͡z̺e"
    english = ["to be, to appear to be, to serve as, to seem like"]
    notes = "nominal copula -- to more exactly approximate the difference between English \"to be\" and \"to seem\", one must use adverbs (like \"underneath\")"
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "že"
        IPA = "d͡z̺es̻t̻u"
        english = ["appearance, role, seeming"]

[[lexicon]]
    word = "daś"
    IPA = "d̻ʲç̩"
    english = ["yesterday", "the day before", "the preceding day", "eve"]
    notes = "the reference time of the context is what clarifies whether it truly means yesterday or whether it refers to the day that precedes some other relevant day"
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "abstract"

[[lexicon]]
    word = "oh"
    IPA = "oʔ"
    english = ["person", "people", "man", "woman", "being", "one"]
    notes = "frequently used in derivation"
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "variable: GOB or NGINT"

[[lexicon]]
    word = "uď"
    IPA = "ud̺"
    english = ["that", "that near you"]
    notes = "medial demonstrative"
    meta.date_added = 2019-06-09
    grammar.POS = "postposition"

[[lexicon]]
    word = "ńoď"
    IPA = "ɲod̺"
    english = ["that", "that over there"]
    notes = "distal demonstrative"
    meta.date_added = 2019-06-09
    grammar.POS = "postposition"

[[lexicon]]
    word = "uň"
    IPA = "un̺"
    english = ["this", "this here"]
    notes = "proximal demonstrative"
    meta.date_added = 2019-06-09
    grammar.POS = "postposition"

[[lexicon]]
    word = "žeź"
    IPA = "d͡z̺eɟ͡ʝ"
    english = ["to see", "to look at", "to watch"]
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "žećstu"
        IPA = "d͡z̺ec͡çɕt̻u"
        english = ["seeing", "sight", "view", "show", "exhibit"]

[[lexicon]]
    word = "eum"
    IPA = "ɯm"
    english = ["to go to", "to arrive at", "to travel to"]
    notes = "implies that the destination was reached"
    meta.date_added = 2019-06-09
    grammar.POS = "verb"
    [grammar.nominalization]
        word = "eumstu"
        IPA = "ɯms̻t̻u"
        english = ["goal", "destination"]

[[lexicon]]
    word = "reu"
    IPA = "ɹ̻ɯ"
    english = ["home", "house", "nest", "dwelling", "burrow"]
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "inanimate"

[[lexicon]]
    word = "meo"
    IPA = "mɤ"
    english = ["caregiver", "wet nurse", "parent", "mother", "father", "mom", "dad", "aunt", "uncle", "grandparent", "grandmother", "grandfather", "grandma", "grandpa"]
    notes = "used to refer to a caregiver with whom the person in question has a particularly close, affectionate relationship"
    meta.date_added = 2019-06-09
    grammar.POS = "noun"
    grammar.noun_class = "variable: GOB or NGINT"

 