# This is the lexicon for Bethany E. Toma's Enłalen language

[metadata]
last_edited = 2019-11-18

[[lexicon]]
    word = 
    IPA = 
    english = 
    meta.date_added = 
    old.root = 
    old.ortho = 